export default () => ({
    counter: 0,
    // activeBack:false,
    showCard:false,
    bodyScrollHide:false,
    showHead:true,
    loadRate:0,
    rateTime:0,
    showLoading:true,
    sourcRoot:window.location.hostname=='localhost'?"":"http://kasakii.com",
    // sourcRoot:window.location.hostname=='localhost'?"":"https://kasakii0428.oss-cn-shanghai.aliyuncs.com",
    // sourcRoot:window.location.hostname=='localhost'?"":window.location.hostname=='www.kasakii.com'?"http://www.kasakii.com":"https://kasakii0428.oss-cn-shanghai.aliyuncs.com",
    // sourcRoot:"",
    // sourcRoot:"http://www.kasakii.com",
    // sourcRoot:'https://kasakii0428.oss-cn-shanghai.aliyuncs.com',
})